/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Scientific } from './Scientific';

export class ObjectSpeed {
    'lng': Scientific;
    'lat': Scientific;
    'distance': Scientific;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "lng",
            "baseName": "lng",
            "type": "Scientific",
            "format": ""
        },
        {
            "name": "lat",
            "baseName": "lat",
            "type": "Scientific",
            "format": ""
        },
        {
            "name": "distance",
            "baseName": "distance",
            "type": "Scientific",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ObjectSpeed.attributeTypeMap;
    }

    public constructor() {
    }
}

