/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class SignedAngle {
    'sign': number;
    'deg': number;
    'min': number;
    'sec': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sign",
            "baseName": "sign",
            "type": "number",
            "format": ""
        },
        {
            "name": "deg",
            "baseName": "deg",
            "type": "number",
            "format": ""
        },
        {
            "name": "min",
            "baseName": "min",
            "type": "number",
            "format": ""
        },
        {
            "name": "sec",
            "baseName": "sec",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SignedAngle.attributeTypeMap;
    }

    public constructor() {
    }
}

